events { }
http {

    upstream servidores {
        server server1:5003;
        server server2:5004;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://servidores;
        }
    }
}